import type { Collection, SavedItem } from "./types";

function isoDaysAgo(days: number, hour = 12) {
  const value = new Date();
  value.setDate(value.getDate() - days);
  value.setHours(hour, 24, 0, 0);
  return value.toISOString();
}

export const seedItems: SavedItem[] = [
  {
    id: "silk-dress",
    title: "The black dress with the perfect drape",
    creator: "Mira Sethi",
    handle: "@miraedits",
    savedAt: isoDaysAgo(0, 9),
    receivedAt: isoDaysAgo(0, 9),
    category: "Fashion",
    domain: "shop.example",
    destinationUrl: "https://example.com/black-dress",
    reelUrl: "https://www.instagram.com/reel/example-dress",
    notes: "Check the size guide before ordering. Saved from the graduation edit.",
    tags: ["graduation", "black", "wishlist"],
    collectionIds: ["wishlist"],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 0,
    variant: "tall",
  },
  {
    id: "barrier-serum",
    title: "Barrier serum for dry skin days",
    creator: "Aanya Kapoor",
    handle: "@skinnotes",
    savedAt: isoDaysAgo(0, 14),
    category: "Beauty",
    domain: "beauty.example",
    destinationUrl: "https://example.com/barrier-serum",
    reelUrl: "https://www.instagram.com/reel/example-serum",
    notes: "Fragrance-free option mentioned around 0:18.",
    tags: ["skincare", "dry skin"],
    collectionIds: ["wishlist"],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 1,
    variant: "standard",
  },
  {
    id: "exam-notes",
    title: "Active recall notes that finally make sense",
    creator: "Nina Studies",
    handle: "@ninastudies",
    savedAt: isoDaysAgo(1, 17),
    category: "Study",
    domain: "notion.so",
    destinationUrl: "https://www.notion.so/templates",
    reelUrl: "https://www.instagram.com/reel/example-notes",
    notes: "Duplicate the template before the next exam block.",
    tags: ["exams", "notes", "template"],
    collectionIds: ["study-reset"],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 2,
    variant: "portrait",
  },
  {
    id: "design-course",
    title: "A practical design systems course",
    creator: "Studio Field",
    handle: "@studiofield",
    savedAt: isoDaysAgo(3, 11),
    category: "Courses",
    domain: "coursera.org",
    destinationUrl: "https://www.coursera.org/browse/arts-and-humanities/design-and-product",
    reelUrl: "https://www.instagram.com/reel/example-course",
    notes: "Six weeks. Project-based and beginner friendly.",
    tags: ["design", "course"],
    collectionIds: ["study-reset"],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 3,
    variant: "standard",
  },
  {
    id: "keyboard-setup",
    title: "Compact keyboard for a tiny study desk",
    creator: "Dev Desk",
    handle: "@devdeskdaily",
    savedAt: isoDaysAgo(6, 19),
    category: "Technology",
    domain: "example.com",
    destinationUrl: "https://example.com/compact-keyboard",
    notes: "Compare the quiet switches before buying.",
    tags: ["desk", "keyboard"],
    collectionIds: ["study-reset"],
    state: "active",
    reelStatus: "unknown",
    metadataStatus: "complete",
    spriteIndex: 4,
    variant: "short",
  },
  {
    id: "quiet-cafe",
    title: "The quiet cafe near the old book market",
    creator: "Around Delhi",
    handle: "@arounddelhi",
    savedAt: isoDaysAgo(10, 16),
    category: "Food",
    domain: "maps.google.com",
    destinationUrl: "https://maps.google.com",
    reelUrl: "https://www.instagram.com/reel/example-cafe",
    notes: "Go before 11am; the upstairs corner has charging points.",
    tags: ["cafe", "weekend"],
    collectionIds: ["slow-weekends"],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 5,
    variant: "portrait",
  },
  {
    id: "coastal-route",
    title: "A slow coastal route for the semester break",
    creator: "Elsewhere Club",
    handle: "@elsewhereclub",
    savedAt: isoDaysAgo(16, 10),
    category: "Travel",
    domain: "maps.google.com",
    destinationUrl: "https://maps.google.com",
    reelUrl: "https://www.instagram.com/reel/example-coast",
    notes: "Save the ferry timetable separately.",
    tags: ["coast", "summer"],
    collectionIds: ["slow-weekends"],
    state: "active",
    reelStatus: "deleted",
    metadataStatus: "complete",
    spriteIndex: 6,
    variant: "tall",
  },
  {
    id: "running-plan",
    title: "Beginner 5K plan that does not feel punishing",
    creator: "Move Kindly",
    handle: "@movekindly",
    savedAt: isoDaysAgo(22, 8),
    category: "Fitness",
    domain: "example.com",
    destinationUrl: "https://example.com/5k-plan",
    notes: "Three sessions a week, mostly easy pace.",
    tags: ["running", "5k"],
    collectionIds: [],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 7,
    variant: "standard",
  },
  {
    id: "ceramic-lamp",
    title: "Sculptural lamp for the reading corner",
    creator: "Soft Spaces",
    handle: "@softspaces",
    savedAt: isoDaysAgo(34, 18),
    category: "Home",
    domain: "example.com",
    destinationUrl: "https://example.com/ceramic-lamp",
    reelUrl: "https://www.instagram.com/reel/example-lamp",
    notes: "Warm bulb only. The smaller size is enough.",
    tags: ["lighting", "home"],
    collectionIds: ["wishlist"],
    state: "archived",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 8,
    variant: "portrait",
  },
  {
    id: "film-list",
    title: "Twelve quiet films for a rainy weekend",
    creator: "The Film Margin",
    handle: "@filmmargin",
    savedAt: isoDaysAgo(41, 21),
    category: "Entertainment",
    domain: "letterboxd.com",
    destinationUrl: "https://letterboxd.com",
    reelUrl: "https://www.instagram.com/reel/example-films",
    notes: "Start with the three under 100 minutes.",
    tags: ["films", "rainy day"],
    collectionIds: ["slow-weekends"],
    state: "active",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 9,
    variant: "short",
  },
  {
    id: "portfolio-notes",
    title: "Portfolio review notes for internship season",
    creator: "Career Edit",
    handle: "@careeredit",
    savedAt: isoDaysAgo(52, 13),
    category: "Career",
    domain: "example.com",
    destinationUrl: "https://example.com/portfolio-review",
    notes: "Add the impact line to each case study.",
    tags: ["portfolio", "internship"],
    collectionIds: ["study-reset"],
    state: "active",
    reelStatus: "unknown",
    metadataStatus: "incomplete",
    spriteIndex: 10,
    variant: "standard",
  },
  {
    id: "pasta-place",
    title: "Handmade pasta for the next birthday dinner",
    creator: "Table for Two",
    handle: "@tablefortwo",
    savedAt: isoDaysAgo(68, 20),
    category: "Food",
    domain: "maps.google.com",
    destinationUrl: "https://maps.google.com",
    notes: "Reservation opens 14 days ahead.",
    tags: ["dinner", "birthday"],
    collectionIds: ["slow-weekends"],
    state: "trashed",
    reelStatus: "available",
    metadataStatus: "complete",
    spriteIndex: 11,
    variant: "portrait",
  },
];

export const seedCollections: Collection[] = [
  {
    id: "wishlist",
    title: "Quiet wishlist",
    description: "Things worth considering, not impulse buying.",
    itemIds: ["silk-dress", "barrier-serum", "ceramic-lamp"],
    shared: false,
    updatedAt: isoDaysAgo(0),
  },
  {
    id: "study-reset",
    title: "Study reset",
    description: "Courses, tools, and systems for the next semester.",
    itemIds: ["exam-notes", "design-course", "keyboard-setup", "portfolio-notes"],
    shared: true,
    updatedAt: isoDaysAgo(1),
  },
  {
    id: "slow-weekends",
    title: "Slow weekends",
    description: "Places, films, and small plans for free Saturdays.",
    itemIds: ["quiet-cafe", "coastal-route", "film-list", "pasta-place"],
    shared: false,
    updatedAt: isoDaysAgo(7),
  },
];
